#!/usr/bin/env bash
# Tool Name :- IP-Hunter
# Author :- Ethical Hacker Koushik
# Date :- 17/12/2020

case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.traceip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ip-hunter -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .IP-Hunter.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    
    echo "Usage: ip-hunter

[command]... [arguments]..."
    echo "     Hello Dear V20.02.11 by Koushik©™
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h                  to show help."
    echo " -u                  to update ip-hunter."
    echo " help                to show help."
    echo " update              to update ip-hunter."
    echo " start               to start ip-hunter menu."
esac
